Resources:
  TeamcityLambdaRunner:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "TeamcityLambdaRunner-java11"
      PackageType: Image
      ImageConfig:
        Command: ["jetbrains.buildServer.runner.lambda.TasksRequestHandler::handleRequest"]
      MemorySize: 4098
      Timeout: 900
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .